# Writes a small amount of data to gzipped csv files in S3.

backend: csv
# This can be anything smart_open can handle, a local directory or
# an S3 bucket, etc., but importing to ClickHouse only supports S3 right now
# https://pypi.org/project/smart-open/
csv_output_destination: s3://.../logs/large_test/
csv_load_from_s3_after: false

# Run options
log_dir: logs
num_xapi_batches: 3
batch_size: 100

# This number is used for each QueueBackend that use workers, so the number of threads if
# multiplicative. Generally this performs best less than 10, as more threads will cost more
# in context switching than they save.
num_workers: 4

# Overall start and end date for the entire run
start_date: 2014-01-01
end_date: 2023-11-27

# All courses will be this long, and be fit into the start / end dates
# This must be less than end_date - start_date days.
course_length_days: 120

# The size of the test
num_organizations: 3
num_actors: 10

# This replicates users updating their profiles several times, creating
# more rows
num_actor_profile_changes: 5

# How many of each size course to create. The sum of these is the total number
# of courses created for the test.
num_course_sizes:
  small: 1
  medium: 1
  large: 1
  huge: 1

# How many times each course will be "published", this creates a more realistic
# distribution of course blocks where each course can be published dozens or
# hundreds of times while it is being developed.
num_course_publishes: 100

# Course size configurations, how many of each type of object are created for
# each course of this size. "actors" must be less than or equal to "num_actors".
# For a course of this size to be created it needs to exist both here and in
# "num_course_sizes".
course_size_makeup:
  small:
    actors: 5
    problems: 20
    videos: 10
    chapters: 3
    sequences: 10
    verticals: 20
    forum_posts: 20
  medium:
    actors: 7
    problems: 40
    videos: 20
    chapters: 4
    sequences: 20
    verticals: 30
    forum_posts: 40
  large:
    actors: 10
    problems: 80
    videos: 30
    chapters: 5
    sequences: 40
    verticals: 80
    forum_posts: 200
  huge:
    actors: 10
    problems: 160
    videos: 40
    chapters: 10
    sequences: 50
    verticals: 100
    forum_posts: 1000
