THEMES = {
    "default": [
        # Style name                    # 16-color style                        # Monochrome style          # 88, 256 and true-color style
        (
            "heading",
            "light gray,underline",
            "default",
            "underline",
            "g93,underline",
            "default",
        ),
        ("menubar", "black", "light gray", "standout", "#111", "#bbb"),
        ("scrollbar", "light gray", "default", "default", "#444", "default"),
        ("shortcutbar", "black", "light gray", "standout", "#111", "#bbb"),
        ("body_text", "light gray", "default", "default", "#ddd", "default"),
        ("error_text", "dark red", "default", "default", "dark red", "default"),
        ("warning_text", "yellow", "default", "default", "#ba4", "default"),
        (
            "inactive_text",
            "dark gray",
            "default",
            "default",
            "dark gray",
            "default",
        ),
        ("buttons", "light green,bold", "default", "default", "#00a533", "default"),
        ("list_focus", "black", "light gray", "standout", "#111", "#aaa"),
        ("list_off_focus", "black", "dark gray", "standout", "#111", "#777"),
        ("list_trusted", "dark green", "default", "default", "#6b2", "default"),
        ("list_focus_trusted", "black", "light gray", "standout", "#150", "#aaa"),
        ("list_unknown", "dark gray", "default", "default", "#bbb", "default"),
        ("list_normal", "dark gray", "default", "default", "#bbb", "default"),
        ("list_untrusted", "dark red", "default", "default", "#a22", "default"),
        ("list_focus_untrusted", "black", "light gray", "standout", "#810", "#aaa"),
        ("list_unresponsive", "yellow", "default", "default", "#b92", "default"),
        (
            "list_focus_unresponsive",
            "black",
            "light gray",
            "standout",
            "#530",
            "#aaa",
        ),
        (
            "topic_list_normal",
            "light gray",
            "default",
            "default",
            "#ddd",
            "default",
        ),
        ("browser_controls", "light gray", "default", "default", "#bbb", "default"),
        ("progress_full", "black", "light gray", "standout", "#111", "#bbb"),
        ("progress_empty", "light gray", "default", "default", "#ddd", "default"),
    ],
}
